{
    "name": "Odoo Learning",
    "summary": "This Model Create by Mitesh Amin. For Fresher",
    "author": "Mitesh Amin",
    "data": [
        "security/ir.model.access.csv",
        "views/odoo_decorators/api_ondelete.xml",
        "views/odoo_decorators/api_model_create_multi.xml",
        "views/odoo_decorators/api_returns.xml",
        "views/odoo_decorators/api_constraints.xml",
        "views/odoo_decorators/api_depends.xml",
        "views/odoo_decorators/api_onchange.xml",
        "views/odoo_decorators/api_model.xml",
        "views/odoo_views/odoo_kanban.xml",
        "views/odoo_views/odoo_cohort.xml",
        "views/odoo_views/odoo_gantt.xml",
        "views/odoo_views/odoo_pivot.xml",
        "views/odoo_views/odoo_graph.xml",
        "views/odoo_views/odoo_calender.xml",
        "views/odoo_views/odoo_search.xml",
        "views/odoo_views/odoo_form.xml",
        "views/odoo_views/odoo_tree.xml",
        "views/odoo_fields/many2many_fields.xml",
        "views/odoo_fields/relational_1_field.xml",
        "views/odoo_fields/monetary_fields.xml",
        "views/odoo_fields/text_fields.xml",
        "views/odoo_fields/selection_fields.xml",
        "views/odoo_fields/html_fields.xml",
        "views/odoo_fields/binary_fields.xml",
        "views/odoo_fields/boolean_fields.xml",
        "views/odoo_fields/date_time_fields.xml",
        "views/odoo_fields/date_fields.xml",
        "views/odoo_fields/float_fields.xml",
        "views/odoo_fields/integer_fields.xml",
        "views/odoo_fields/char_fields.xml",
        "views/class_attributes/_inherits_atttribute.xml",
        "views/class_topic/create_model.xml",
        "views/class_topic/abstract.xml",
        'wizard/wizard.xml',
        "views/class_topic/transient_model.xml",
        "views/class_attributes/_name_attribute.xml",
        "views/class_attributes/_description_attribute.xml",
        "views/class_attributes/_rec_name_attribute.xml",
        "views/class_attributes/_order_attribute.xml",
        "views/class_attributes/_inherit_attribute.xml",
        "views/odoo_learning_root.xml"
    ],
    "depends": ['base'],
    "version": "17.0.0.1",
    "license": "LGPL-3",
}
