from . import odoo_learning_root_menu
from .class_topic import create_model
from .class_topic import abstarct_model
from .class_topic import transient_model
from .class_attributes import name_attribute
from .class_attributes import description_attribute
from .class_attributes import rec_name_attribute
from .class_attributes import order_attribute
from .class_attributes import inherit_attribute
from .class_attributes import inherits_attribute
from .odoo_fields import char_fields
from .odoo_fields import integer_fields
from .odoo_fields import float_fields
from .odoo_fields import date_fields
from .odoo_fields import date_time_fields
from .odoo_fields import boolean_fields
from .odoo_fields import binary_fields
from .odoo_fields import html_fields
from .odoo_fields import selection_fields
from .odoo_fields import text_fields
from .odoo_fields import monetary_fields
from .odoo_fields import relational_1_field
from .odoo_fields import many2many_fields
from .odoo_attributes import reqired_attribute
from .odoo_attributes import default_attribute
from .odoo_attributes import help_attribute
from .odoo_attributes import index_attribute
from .odoo_attributes import string_attribute
from .odoo_attributes import readonly_attribute
from .odoo_attributes import compute_attribute
from .odoo_attributes import store_attribute
from .odoo_attributes import ondelete_attribute
from .odoo_attributes import copy_attribute
from .odoo_attributes import domain_attribute
from .odoo_attributes import related_attribute
from .odoo_attributes import context_attribute
from .odoo_attributes import tracking_attribute
from .odoo_attributes import column_attribute
from .odoo_views import odoo_tree
from .odoo_views import odoo_form
from .odoo_views import odoo_search
from .odoo_views import odoo_calender
from .odoo_views import odoo_graph
from .odoo_views import odoo_pivot
from .odoo_views import odoo_gantt
from .odoo_views import odoo_cohort
from .odoo_views import odoo_kanban
from .odoo_decorators import api_model
from .odoo_decorators import api_onchange
from .odoo_decorators import api_depends
from .odoo_decorators import api_constraints
from .odoo_decorators import api_returns
from .odoo_decorators import api_model_create_multi
from .odoo_decorators import api_ondelete
from .odoo_orm_methods import create_method
from .odoo_orm_methods import write_method
from .odoo_orm_methods import unlink_method
from .odoo_orm_methods import search_method
from .odoo_orm_methods import copy_method
from .odoo_orm_methods import browse_method
from .odoo_orm_methods import read_method
from .odoo_orm_methods import search_count_method
from .odoo_orm_methods import search_read
from .odoo_orm_methods import read_group
from .odoo_orm_methods import name_search
from .odoo_orm_methods import name_get
from .odoo_error_handling import exception_handling
from .odoo_error_handling import validation_error
