from . import odoo_learning_root_menu
from .class_topic import create_model
from .class_topic import abstarct_model
from .class_topic import transient_model
from .class_attributes import name_attribute
from .class_attributes import description_attribute
from .class_attributes import rec_name_attribute
from .class_attributes import order_attribute
from .class_attributes import inherit_attribute
from .class_attributes import inherits_attribute
from .odoo_fields import char_fields
from .odoo_fields import integer_fields
from .odoo_fields import float_fields
from .odoo_fields import date_fields
from .odoo_fields import date_time_fields
from .odoo_fields import boolean_fields
from .odoo_fields import binary_fields
from .odoo_fields import html_fields
from .odoo_fields import selection_fields
from .odoo_fields import text_fields
from .odoo_fields import monetary_fields
from .odoo_views import odoo_tree
from .odoo_views import odoo_form
from .odoo_views import odoo_search
from .odoo_views import odoo_calender
from .odoo_views import odoo_graph
from .odoo_views import odoo_pivot

